name: Check package

on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]

jobs:
  check-package:
    uses: Lightning-AI/devtools/.github/workflows/check-package.yml@main
    with:
      import-name: "torchmetrics"
      pypi-name: "torchmetrics"
