name: Check schema

on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]

jobs:
  check-schema:
    uses: Lightning-AI/devtools/.github/workflows/check-schema.yml@main
