name: Check code

on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]

jobs:
  check-code:
    uses: Lightning-AI/devtools/.github/workflows/check-code.yml@main
